name: SafeSpawn
main: com.ath.bukkit.safespawn.SafeSpawnPlugin
version: 0.1 Beta
author: angryBits
description: My own special blend of tools for running a minecraft server
commands:
  rules:
    description: Rules for the server
